services:
  spring-1:
    build: .
    restart: always
    environment:
      - SERVER_PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      master-redis:
        condition: service_healthy
      slave-redis-a:
        condition: service_healthy
      slave-redis-b:
        condition: service_healthy
      mysql:
        condition: service_healthy

  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: spoteditor
      MYSQL_DATABASE: spoteditor
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD" ]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  master-redis:
    container_name: master-redis
    image: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  slave-redis-a:
    container_name: slave-redis-a
    image: redis
    ports:
      - "7001:6379"
    command: redis-server --slaveof master-redis 6379
    depends_on:
      master-redis:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  slave-redis-b:
    container_name: slave-redis-b
    image: redis
    ports:
      - "7002:6379"
    command: redis-server --slaveof master-redis 6379
    depends_on:
      master-redis:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  redis-commander:
    platform: linux/amd64
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=master:master-redis:6379,slave-a:slave-redis-a:6379,slave-b:slave-redis-b:6379
    ports:
      - "8081:8081"
    depends_on:
      - master-redis
      - slave-redis-a
      - slave-redis-b